\i ./01_families.sql
\i ./02_user_types.sql
\i ./03_users.sql
\i ./05_quests.sql
\i ./06_quest_tasks.sql
\i ./07_quest_reviews.sql
\i ./08_prizes.sql
\i ./09_stores.sql
\i ./10_store_prizes.sql
\i ./11_discounts.sql
\i ./12_user_prizes.sql